# Generated by Django 5.1.2 on 2024-11-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_alter_cartorderitems_options_coupon_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_codee',
        ),
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='user_directory_path'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_store.product'),
        ),
    ]
