# Generated by Django 5.1.2 on 2024-11-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0008_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='app_store.coupon'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.IntegerField(default=5, help_text='Entered number is consider as percentage'),
        ),
    ]
