# Generated by Django 5.1.2 on 2024-11-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0009_cartorderitems_coupon_alter_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
