# Generated by Django 5.1.2 on 2024-12-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(blank=True, help_text='Shop email', max_length=100, null=True),
        ),
    ]
